apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: my-apps
  name: redis-cart-virtual-router
spec:
  listeners:
    - portMapping:
        port: 6379
        protocol: http
  routes:
    - name: redis-cart-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: redis-cart
              weight: 1
