apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: adservice
  namespace: my-apps
spec:
  awsName: adservice.my-apps.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: adservice-virtual-router
