apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: my-apps
  name: adservice-virtual-router
spec:
  listeners:
    - portMapping:
        port: 9555
        protocol: grpc
  routes:
    - name: adservice-route
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: adservice
              weight: 1
